In [1]:
import pandas as pd

df = pd.read_csv('data/2022-07-v2.csv', nrows=100000)
df.head()

,platform,id_utilisateur,page,page_gabarit,page_arbo_niveau_1,page_arbo_niveau_2,page_arbo_niveau_3,heure_evenement,type,rien_1,rien_2,token_1,token_2,visites
0,NPC,86700-0d0d5n5n0d1f0d0d9v5n7r2h0d0d,Particulier,accueil_particuliers_et_BP,particulier,NaN,NaN,2022-07-01 00:59:58.537,chargement_page,NaN,NaN,1B9016323EA73F76B192B5591182E81A,C04FD419E23E1897B46CA63FE602372FB423AD93,1
1,NPC,86700-0d0d5n7r0d3j0d0d3j5n2h2h0d0d,Ma_synthese_de_comptes,fonctions_connectees_synthese_des_comptes,particulier,operations,synthese,2022-07-01 00:59:56.543,chargement_page,NaN,NaN,FDFCF59B9B9739E3939C21D2B592FC66,31F142C69D6A0491E6361D5C316EB3BCDE8FE43F,1
2,NPC,86700-0d0d2h0d0d9v0d0d3j7r3j1f1f0d,Ma_messagerie,fonctions_connectees_pumigrees,particulier,operations,profil,2022-07-01 00:59:53.256,chargement_page,NaN,NaN,E50C3B5E95BB37C28656FA9144A26833,85630499969F8C46F7B03985ADF1AFF1C17B13B8,1
3,NPC,86700-0d0d3j5n0d3j0d0d7r9v1f2h0d0d,connexion_client,accueil_particuliers_et_BP,particulier,NaN,NaN,2022-07-01 00:59:50.691,click_utilisateur,NaN,NaN,D7FE8C4563E135EDB85806825F8FE6CA,A119AE60204EF6E4726D99B37A537BEAE0FB413D,1
4,NPC,86700-0d0d0d3j0d6p0d0d5n3j8t7r0d0d,Mon_detail_de_compte,fonctions_connectees_detail_comptes_contrats,particulier,operations,synthese,2022-07-01 00:59:50.107,chargement_page,NaN,NaN,EE575490FE73363BA8A5BB2A9DB76E8C,E9F63AA3DF3EEFEFA5FD532ED0DC2A1DE2873B8A,1

In [2]:
# moyenne vite fait
df.groupby('id_utilisateur').size().sort_values(ascending=False).mean()

7.386069872220991

In [3]:
# lignes par utilisateur
df.groupby('id_utilisateur').size().sort_values(ascending=False).head()

id_utilisateur
86700-0d0d2h1f0d9v0d0d8t9v5n0d0d0d    235
86700-0d0d2h9v0d8t0d0d1f5n2h4l1f0d    170
86700-0d0d3j7r0d5n0d0d6p1f0d1f0d0d    170
86700-0d0d5n0d0d9v0d0d5n0d2h0d0d0d    139
86700-0d0d3j8t0d5n0d0d0d5n1f6p0d0d    115
dtype: int64

In [4]:
# lignes par utilisateur et token (on remarque que le plus gros clickeur disparait)
df.groupby(['id_utilisateur', "token_1", "token_2"]).size().sort_values(ascending=False).head(20)

id_utilisateur                      token_1                           token_2
86700-0d0d2h9v0d8t0d0d1f5n2h4l1f0d  88AE21FE694C3324A2180098837B77FE  341285919AA2AE9EEDEEBEE179A8F071E4C21578    170
86700-0d0d3j7r0d5n0d0d6p1f0d1f0d0d  83CB6F9F0BC13772AC63F50BA959C9E4  5C63DD98ACC711C764ADDE550C510B6A8A8C3A58    150
86700-0d0d5n0d0d9v0d0d5n0d2h0d0d0d  0D00E6E431153AEE94031435A8DB3CF5  35DF03444EBFF620ECF241DD5722C01DA7C26B2B    139
86700-0d0d3j8t0d5n0d0d0d5n1f6p0d0d  B5CF8BA3F9EE3B42BDC61F2DC324842D  F95C15B1C3F360B1F1C1E8B3011CC71495202A31    115
86700-0d0d0d5n0d1f0d0d6p2h1f4l0d0d  DB07B1032F8B3FE49A114401FEFDF922  E7B58315852A4B6F178863008B1DF80662E09AD6    109
86700-0d0d5n5n0d3j0d0d7r9v3j2h0d0d  C904DDA34F4F3B08B54E98E9E820648F  269413587B321D7FBEAE994B00DDD4259FFF644E    103
86700-0d0d5n9v0d3j0d0d3j1f4l0d0d0d  968579989C42359296D61BA8FD2D8BCA  BCF02E927221157D86C44049E46A4AE602311D7C     98
86700-0d0d5n4l0d9v0d0d3j7r5n1f0d0d  1BF85ABB8B183260AB3E2EF3C4E59EFD  E5EA5C88609C4047D4518A035C26E4AF5B4FD63F     86
86700-0d0d5n4l0d2h0d0d2h6p7r9v0d0d  06A02710E5AB36D2AAE1351FAEB73B05  8E891E4B48AA90C4B1EB3C46362B49A3C436DDB1     80
86700-0d0d2h0d0d4l0d0d0d1f6p4l1f0d  D4B68FCA938D306EBAE2E42894AF577D  C4819E6AAC42E41603E663B5F249A0FC8FFA6664     79
86700-0d0d2h7r0d2h0d0d9v0d8t8t0d0d  C98C02DDBC62316790CF745960E41233  E09E40A2B0A193189AFC85A88F52CEDB0266B873     79
86700-0d0d2h2h0d2h0d0d9v3j4l4l0d0d  CC32BBDB299E38D5A84A37BD939C513C  F42FC94166490D7ED2C9639094884C98B3047C49     78
86700-0d0d0d5n0d8t0d0d0d3j1f5n2h0d  A0B5D1383893367CA52D1C8DD06A6AEF  61568FF19A4F67280A847DB3623058BA2103B5E8     78
86700-0d0d2h8t0d9v0d0d8t2h7r1f0d0d  2B4496ABD2DA37E9A4F36960EAD3518C  4E51D48D685A18E2941DC934725D94D0E7D7DC51     75
86700-0d0d2h1f0d1f0d0d0d5n0d1f1f0d  3FD3C2AA2D383DC387236AC0F2862E4B  DB12F67B5F042E02C00EDD53D63499670314882F     72
86700-0d0d3j3j0d1f0d0d3j0d4l2h1f0d  53EDEE28F842310AA7837887CB2EB498  109FB894A39985DF1B1AD622DF3950F885C587DF     68
86700-0d0d5n9v0d3j0d0d7r9v4l1f0d0d  CD4478F3386239D596B4537A070A5A77  77A859E4F32866E154D50086D95DACA569BA555E     67
86700-0d0d3j8t0d9v0d0d7r9v3j2h0d0d  047E314E80403E42BFA7E34E408C498E  35311FC306B0C84FD9780E8055A0ADBC843FB8B6     67
86700-0d0d2h4l0d3j0d0d9v5n4l3j0d0d  7531B83EE9293C959C9AFA11B9D7D919  113371B35FC12F02D0BF3DC0DEB1DAE9E8AD6093     63
86700-0d0d0d6p0d6p0d0d9v3j7r4l0d0d  3BC66EE9F99D3591BF90E4CAF0FFDE6C  9305A11A417E1642E6BA2E4E36AA377D6FD8E61E     63
dtype: int64

In [ ]:
# Conclusion 1 : un utilisateur peut avoir plusieurs tokens

Cas particulier

In [7]:
user = df[df["id_utilisateur"] == "86700-0d0d3j3j0d1f0d0d3j0d4l2h1f0d"]
user.head()

,platform,id_utilisateur,page,page_gabarit,page_arbo_niveau_1,page_arbo_niveau_2,page_arbo_niveau_3,heure_evenement,type,rien_1,rien_2,token_1,token_2,visites
74051,NPC,86700-0d0d3j3j0d1f0d0d3j0d4l2h1f0d,Banque_privee,accueil_particuliers_et_BP,banque-privee,NaN,NaN,2022-07-01 11:54:02.186,chargement_page,NaN,NaN,53EDEE28F842310AA7837887CB2EB498,109FB894A39985DF1B1AD622DF3950F885C587DF,1
74135,NPC,86700-0d0d3j3j0d1f0d0d3j0d4l2h1f0d,Ma_synthese_de_comptes,fonctions_connectees_synthese_des_comptes,banque-privee,operations,synthese,2022-07-01 11:53:56.787,chargement_page,NaN,NaN,53EDEE28F842310AA7837887CB2EB498,109FB894A39985DF1B1AD622DF3950F885C587DF,1
74263,NPC,86700-0d0d3j3j0d1f0d0d3j0d4l2h1f0d,Consultez_le_detail_de_vos_comptes,fonctions_connectees_detail_comptes_contrats,professionnel,operations,synthese,2022-07-01 11:53:48.819,chargement_page,NaN,NaN,53EDEE28F842310AA7837887CB2EB498,109FB894A39985DF1B1AD622DF3950F885C587DF,1
74317,NPC,86700-0d0d3j3j0d1f0d0d3j0d4l2h1f0d,Votre_synthese,fonctions_connectees_synthese_des_comptes,professionnel,operations,synthese,2022-07-01 11:53:45.159,chargement_page,NaN,NaN,53EDEE28F842310AA7837887CB2EB498,109FB894A39985DF1B1AD622DF3950F885C587DF,1
74333,NPC,86700-0d0d3j3j0d1f0d0d3j0d4l2h1f0d,Virement_validation,fonctions_connectees_virement,professionnel,operations,paiements-encaissements,2022-07-01 11:53:43.803,click_utilisateur,NaN,NaN,53EDEE28F842310AA7837887CB2EB498,109FB894A39985DF1B1AD622DF3950F885C587DF,1

In [10]:
len(user)

68

In [19]:
user.token_1.unique()

array(['53EDEE28F842310AA7837887CB2EB498'], dtype=object)

In [20]:
user.token_2.unique()

array(['109FB894A39985DF1B1AD622DF3950F885C587DF'], dtype=object)

In [60]:
# Ici un seul token pour l'utilisateur

In [23]:
user = df[df["id_utilisateur"] == "86700-0d0d2h1f0d9v0d0d8t9v5n0d0d0d"]
user.head()

,platform,id_utilisateur,page,page_gabarit,page_arbo_niveau_1,page_arbo_niveau_2,page_arbo_niveau_3,heure_evenement,type,rien_1,rien_2,token_1,token_2,visites
204,NPC,86700-0d0d2h1f0d9v0d0d8t9v5n0d0d0d,Particulier,accueil_particuliers_et_BP,particulier,NaN,NaN,2022-07-01 00:55:37.767,chargement_page,NaN,NaN,CDF0C6D0EE5C3B83ADD1B7C1FF227711,DD431F286E116622F1FBAF9FD2360EBDF5318A39,1
215,NPC,86700-0d0d2h1f0d9v0d0d8t9v5n0d0d0d,Ma_synthese_de_comptes,fonctions_connectees_synthese_des_comptes,particulier,operations,synthese,2022-07-01 00:55:29.196,chargement_page,NaN,NaN,CDF0C6D0EE5C3B83ADD1B7C1FF227711,DD431F286E116622F1FBAF9FD2360EBDF5318A39,1
223,NPC,86700-0d0d2h1f0d9v0d0d8t9v5n0d0d0d,Particulier,accueil_particuliers_et_BP,particulier,NaN,NaN,2022-07-01 00:55:15.409,chargement_page,NaN,NaN,CDF0C6D0EE5C3B83ADD1B7C1FF227711,DD431F286E116622F1FBAF9FD2360EBDF5318A39,1
261,NPC,86700-0d0d2h1f0d9v0d0d8t9v5n0d0d0d,Particulier,accueil_particuliers_et_BP,particulier,NaN,NaN,2022-07-01 00:54:21.693,chargement_page,NaN,NaN,53B4F2E22ACC3BFAA523C2CDB071E5B5,8458CA6E0D7EB7B659F3B0C044CC40E4FAEFE453,1
264,NPC,86700-0d0d2h1f0d9v0d0d8t9v5n0d0d0d,Ma_messagerie,fonctions_connectees_pumigrees,particulier,operations,profil,2022-07-01 00:54:19.546,chargement_page,NaN,NaN,53B4F2E22ACC3BFAA523C2CDB071E5B5,8458CA6E0D7EB7B659F3B0C044CC40E4FAEFE453,1

In [24]:
user.to_csv("tmp/user.csv", index=False)

In [25]:
user.token_1.unique()

array(['CDF0C6D0EE5C3B83ADD1B7C1FF227711',
       '53B4F2E22ACC3BFAA523C2CDB071E5B5',
       '497754F6F8D53D5AB29163CE4E8398D1',
       'EE81ABE0443F36A5A21921D4E38B5DFB',
       '100D6B07E7C03F71B43219E312CEAB06',
       'F3668ECFDFE133DDBA0BCCBB36AC2937',
       '2F59C2B38A7D38E2B50409C4E49A9AAF',
       'CB5A64CCEC9C34EF87EBDF8D3F2BA437',
       '1EA2387062FC3B22A564548413249AD6',
       '1C60C3F806C134F2AE6978D726312F5D',
       '93582B25C45B3BB9A68398BF1D986256',
       '6A95282E01FC324693F85FFF2F5F2E45',
       'DFDE150F60A53844959DD60E568EBA57',
       '2A6FF769409E33EA8DDB26DFA1AAFE52',
       '13B54C93385A3F63B8B420774B314D60',
       '0166689B48D8368BBD02AF51ABCD3FDF',
       'EEA7F167732A3182BAF4D23F8054BB79',
       '50DD48007D0F3A64826AF5BD8530AC28',
       '01C8DBF0E95E3882ADC306B7E12F339F',
       '512DB36E877E3E2F8CADAAD2AC0E448A',
       '2BBCF070018B3BAE9D2DC6B19FA3C649',
       '8A1EC0438AB33C34AE4E576636D24B31',
       '34A44C0517CB30B3A3E1A420796C6AC7',
       'DC0AEB6AE6623B8CAD79A571753F88D8',
       '00FFD9397EE13081B4700D8C81D547EE',
       'A6C6A255721036799901B8F94224E168',
       '5C3B6D48686132428F02EC6A2DCAEB31',
       '740F20E383963323B07632285FAAC75D',
       '4AEF0C3917283C4898C1C81709511842',
       '88F3156E804732BE9A95F0C589CE83CB',
       '47D51D86FD6632B7ADF1BA35A9976ED1',
       '44F1B48352743523AD4F85CFEE03F902',
       '3C2F7C5FAB033543A772FA19AA4A69C5',
       'FE27270E9BBA3B4E86A144978A0CA00D',
       'E5AA8A63559935F09DFD4EFDA8857AB2',
       '7FE70C4EA561353BA770E6408F559111',
       '9480BA03F6303B5EACB524454C1822A4',
       '04F4AD3FAB3C34F7A7ACA6156AA1ECCA',
       '4202796974F0357B9637FE4E36102D3E',
       '86DC95869FFC3F2FA6FA667D58B8579A',
       'B752CE10E7D03E5C904EF6C32E064BBE',
       'A82D960BE1573A57A29A943655EB607E',
       '08A57FEB4D6639E49E0877A07EE54E62',
       'A0E79A2448683899A0BF24B7D39219C0',
       '2791882DE21B32E3997337A1D7749573',
       '592F44D9FB1739FEB01E797D9CB36A5F',
       '4AB8BD4254363F95BBCB7197982BDB65',
       '91F28A4B98FC337488E7B68A6E4DEFF0',
       '562D5E9F8ADA31BD9F6E63F3AB2C6C09',
       '9A78563C458138279F7E69A4630D38B9',
       '6FACBEC1C4BE3AAF9E10EE258620F550',
       '9404A7BCB4833446B5348C84F1D3A4CF',
       'CA4BAB92200D32E3973A86B9D6CF460C',
       '97CFDB5EF6923860A39C8938052AB326',
       'A575AA5A993632C199C6DE18AD03F6B0',
       '2505EDF8D442388C97AF80628D8A156C',
       '6DC3254EBBFE363AB58C43581B87347A'], dtype=object)

In [26]:
user.token_2.unique()

array(['DD431F286E116622F1FBAF9FD2360EBDF5318A39',
       '8458CA6E0D7EB7B659F3B0C044CC40E4FAEFE453',
       '55F48BAFA9635237BF4C2FDF0957F735F03AE6F9',
       '5B0AA5C1EE54018C1297DDB138DB68AABFBD7ED3',
       '15A7C1ABE64713FFE0D6CDDA2E1CA9649CE15A24',
       '8ACCA44AC1F38D46AAF282F325AF85D46A16A3E4',
       'DEA4BBBE341622715D5F2A8300DFDE4802DA4DB1',
       '3614ED14EC0F7D0A306CD6289F6417898710FDCB',
       '7C1D90F2E021072C2C0D13C01191706998B293E9',
       '18FF67901C85199955B84AA3D3970D23E787E045',
       '7F127E290AC7C43C0E69AA130C3F59458494DD50',
       '82E3CB6BB85373FA90E860EA460442A1653F5BA5',
       '2CA792B8CB55495E6DF459DA70596086ACCB152B',
       'DB7D82CF245342A59971E4F26EEC33599A9E267E',
       'BF1A983FD763C7C642C9982DD0502DA531EAB8BD',
       '45CB0C0966D72A7238D25F6458D32CB7D11B7B2C',
       '89E335689454D9E2F5F2F32698F705269937AB06',
       '3A121653E8D1E8DA394539800B9BAE8C55F306E8',
       '6C46E37E591C498058BAF1B970C81508B573A8E5',
       '96ECAB43837E955E59A5C4F7E8123363D842969A',
       '916339A9C67FF3E2FA20264243CA1A8B0EB79EEE',
       'C360A20695BCD3CD0E084073C20789AA95A79D5D',
       '95C756DCA13FBCA799D5D9A020A5FB4F45D0C70D',
       '98FFF3206B4A6B83B76B8C2F261FB1BA5530F149',
       '3C678FFAB83F0E9F282172A5361AE8DB3ACD0CF0',
       '75B70524BF5CEDD835FB138F0EF4ED54AE39EE3A',
       '945242A0413A22B609EB16CFFA6A7D28792E7025',
       'BDCD868CB241E54948A41CABF8598D8FB41B73AB',
       '6D5C91345D67551A2DB3270B2687C08FEBB5DDB9',
       'D2D6E52317F6F632BD5BAD6D76A36E64ACBE3914',
       'BFA4B3A729AE8A11791074D72FE0777D8CD892D5',
       '2556D60122B11C78295E5EC9BD9B705F564482FF',
       '80729F5831FD773754FD89A1E3CB1BB6743ACED7',
       'E617C51259A0A385AE5445E4D2265F8DC1F052B1',
       'F7E3AABE68A7DD26F51CF3F17D3E8427FEF9AAAE',
       '526907DCD355B6FEEA4DCDBFF309257DB431EDD3',
       '2498F65A23826005DB4FFFD97B7FEDF514E65379',
       '0FFE34DEC19B5173BBAA1884BE0A22E21FF61746',
       '2772A888FDE9095D2815597E3EEE76511E6C03CD',
       'BE45BC601BDD440A5F4528FCDD3D335EE77CB606',
       '8A66D7038BB48983FC1587A445197F85108F8174',
       'C199E000910730E4BB696D63270EA06CF6238EAE',
       '89FE813743E44766D7D0639420ECF001F976C88E',
       '75B386EB9F5914F4588DA77548D774196C941B9C',
       '37D0DD7EC9349DA3ED4C25019BD0666928974B34',
       'E960A143E79DCEDF1C50DF7CECC86368EEBB4867',
       'CE2679C4EB45CAAF23B7420EC7A2BB4CA77EEDBE',
       '7EFFFF39D9DD6BA32E7753D2661D731D4DFC5402',
       '95EA12D0B1969A58DA5F16B0CB33027136EBC9EA',
       '344AE7BAD90171803EAFAD21CE21EA6A858698A1',
       'AF49768F01B4EA3389B43B08EF5C531F381FB5D2',
       '86EED26E0D93271220CC2EB1A19EC6E3F106BF87',
       'DA2EDDD6B0AB107B2046BFDBED7D44764FE46D9C',
       '156546CAB13E1FB161F6FEAF8B4D16B975E311B9',
       '4ECF419834A63A577FBC035202067ED3810C7BF5',
       '0EEB2AE19FA2B11A8F58E243242D57344038A483',
       'F20CA6B1AFEA03CAF0FEEA0E4132D1ED0EDD309A'], dtype=object)

In [ ]:
# Conclusion 2 : certains utilisateurs ont peu de token, 1 ou 2 alors que celui ci en as des dizaines. Bot ? Dataset à chier ?

In [27]:
user.type.unique() 
# side note : clique utilisateur peut être important à prendre en compte (plus que chargement de page)

array(['chargement_page', 'click_utilisateur'], dtype=object)

Cas général

In [71]:
# Group by token pour avoir les différents tokens liés aux utilisateurs puis nouveau group by l'id pour avoir le nombre de token différents par utilisateur
user_ntoken = df.groupby(["id_utilisateur", "token_1", "token_2"]).size().groupby("id_utilisateur").size().sort_values(ascending=False).reset_index(name="nb_token")
user_ntoken

                           id_utilisateur  nb_token
0      86700-0d0d2h1f0d9v0d0d8t9v5n0d0d0d        57
1      86700-0d0d0d9v0d8t0d0d5n7r7r3j0d0d         6
2      86700-0d0d5n6p0d2h0d0d0d4l9v9v0d0d         5
3      86700-0d0d0d0d0d6p0d0d5n4l8t8t0d0d         5
4      86700-0d0d3j6p0d3j0d0d8t9v0d8t0d0d         4
...                                   ...       ...
13534  86700-0d0d2h4l0d1f0d0d7r3j3j2h0d0d         1
13535  86700-0d0d2h4l0d1f0d0d7r6p1f7r0d0d         1
13536  86700-0d0d2h4l0d1f0d0d7r6p9v3j0d0d         1
13537  86700-0d0d2h4l0d1f0d0d7r9v2h0d0d0d         1
13538  86700-0d0d5n9v0d9v0d0d9v7r4l1f0d0d         1

[13539 rows x 2 columns]

In [72]:
# Un utilisateur a beaucoup trop de token par rapport aux autres, suspect...

In [73]:
#nombre de lignes par user
user_lines = df.groupby('id_utilisateur').size().sort_values(ascending=False).reset_index(name="nb_lines")
user_lines

                           id_utilisateur  nb_lines
0      86700-0d0d2h1f0d9v0d0d8t9v5n0d0d0d       235
1      86700-0d0d2h9v0d8t0d0d1f5n2h4l1f0d       170
2      86700-0d0d3j7r0d5n0d0d6p1f0d1f0d0d       170
3      86700-0d0d5n0d0d9v0d0d5n0d2h0d0d0d       139
4      86700-0d0d3j8t0d5n0d0d0d5n1f6p0d0d       115
...                                   ...       ...
13534  86700-0d0d3j4l0d3j0d0d3j2h5n5n1f0d         1
13535  86700-0d0d5n6p0d7r0d0d7r1f5n5n0d0d         1
13536  86700-0d0d5n6p0d7r0d0d6p9v9v0d0d0d         1
13537  86700-0d0d5n6p0d7r0d0d6p4l4l3j0d0d         1
13538  86700-0d0d0d6p0d9v0d0d5n0d2h3j0d0d         1

[13539 rows x 2 columns]

In [75]:
user_ntoken.merge(user_lines, on="id_utilisateur", how="left").sort_values(by="nb_lines", ascending=False).head(20)

                           id_utilisateur  nb_token  nb_lines
0      86700-0d0d2h1f0d9v0d0d8t9v5n0d0d0d        57       235
11135  86700-0d0d2h9v0d8t0d0d1f5n2h4l1f0d         1       170
297    86700-0d0d3j7r0d5n0d0d6p1f0d1f0d0d         2       170
5794   86700-0d0d5n0d0d9v0d0d5n0d2h0d0d0d         1       139
1480   86700-0d0d3j8t0d5n0d0d0d5n1f6p0d0d         1       115
9869   86700-0d0d0d5n0d1f0d0d6p2h1f4l0d0d         1       109
604    86700-0d0d5n5n0d3j0d0d7r9v3j2h0d0d         2       108
1008   86700-0d0d2h2h0d2h0d0d9v3j4l4l0d0d         2       107
4946   86700-0d0d5n9v0d3j0d0d3j1f4l0d0d0d         1        98
413    86700-0d0d5n4l0d2h0d0d2h6p7r9v0d0d         2        93
579    86700-0d0d0d6p0d6p0d0d9v3j7r4l0d0d         2        88
4264   86700-0d0d5n4l0d9v0d0d3j7r5n1f0d0d         1        86
10444  86700-0d0d2h7r0d2h0d0d9v0d8t8t0d0d         1        79
8156   86700-0d0d2h0d0d4l0d0d0d1f6p4l1f0d         1        79
7586   86700-0d0d0d5n0d8t0d0d0d3j1f5n2h0d         1        78
11825  86700-0d0d2h8t0d9v0d0d8t2h7r1f0d0d         1        75
661    86700-0d0d2h4l0d3j0d0d9v5n4l3j0d0d         2        73
996    86700-0d0d2h1f0d1f0d0d0d5n0d1f1f0d         2        73
4      86700-0d0d3j6p0d3j0d0d8t9v0d8t0d0d         4        69
3545   86700-0d0d3j3j0d1f0d0d3j0d4l2h1f0d         1        68